# Generated by Django 5.2.6 on 2025-09-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
