# Generated by Django 5.2.6 on 2025-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0002_alter_todoitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
