# Generated by Django 5.2.6 on 2025-09-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0003_alter_todoitem_id'),
        ('User', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
    ]
