# Generated by Django 5.2.6 on 2025-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0004_todoitem_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
