# Generated by Django 5.2.6 on 2025-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0005_alter_todoitem_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
