# Generated by Django 5.2.6 on 2025-09-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0006_alter_todoitem_id'),
        ('User', '0007_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='DONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to='User.user'),
        ),
    ]
