# Generated by Django 5.2.6 on 2025-09-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
        ('User', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to='User.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
