# Generated by Django 5.2.6 on 2025-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0003_alter_todoitem_id'),
        ('TodoList', '0002_todolist_owner_alter_todolist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='lists', to='TodoItem.todoitem'),
        ),
    ]
