# Generated by Django 5.2.6 on 2025-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_todolist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
