# Generated by Django 5.2.6 on 2025-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0004_alter_todolist_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
