# Generated by Django 5.2.6 on 2025-09-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoItem', '0007_todoitem_status_alter_todoitem_assignee'),
        ('TodoList', '0005_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='TodoItem.todoitem'),
        ),
    ]
