# Generated by Django 5.2.6 on 2025-09-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0007_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
